-- Test: Production system
local luaunit = require("luaunit")
local world = require("src.world")
local sim = require("src.sim")
local orders = require("src.orders")
local content = require("src.content")

return {
  ["test-training-produces-unit"] = function()
    local w = world.make_world({seed = 42})
    world.spawn_bang(w, "barracks", {owner = 0, x = 5, y = 3})
    world.spawn_bang(w, "town-centre", {owner = 0, x = 3, y = 3})
    world.add_resource_bang(w, 0, "wood", 200)
    world.add_resource_bang(w, 0, "gold", 200)
    world.add_resource_bang(w, 0, "stone", 200)
    local before = #world.world_entities(w)
    orders.issue_bang(w, orders.train(1, "knight"))
    sim.run_bang(w, content.train_time("knight") + 5)
    local after = #world.world_entities(w)
    luaunit.assertTrue(after > before)
  end,

  ["test-fifo-queue-order"] = function()
    local w = world.make_world({seed = 42})
    world.spawn_bang(w, "barracks", {owner = 0, x = 5, y = 3})
    world.spawn_bang(w, "town-centre", {owner = 0, x = 3, y = 3})
    world.add_resource_bang(w, 0, "wood", 500)
    world.add_resource_bang(w, 0, "gold", 500)
    world.add_resource_bang(w, 0, "stone", 500)
    orders.issue_bang(w, orders.train(1, "pikeman"))
    orders.issue_bang(w, orders.train(1, "knight"))
    sim.run_bang(w, content.train_time("knight") + 2)
    local prod = world.world_get(w, 1, "producer")
    luaunit.assertEquals(prod.queue[1], "pikeman")
  end,

  ["test-wrong-building-rejection"] = function()
    local w = world.make_world({seed = 42})
    world.spawn_bang(w, "town-centre", {owner = 0, x = 3, y = 3})
    world.add_resource_bang(w, 0, "wood", 500)
    world.add_resource_bang(w, 0, "gold", 500)
    world.add_resource_bang(w, 0, "stone", 500)
    local before = #world.world_entities(w)
    orders.issue_bang(w, orders.train(1, "knight"))
    sim.run_bang(w, 5)
    local after = #world.world_entities(w)
    luaunit.assertEquals(after, before)
  end,

  ["test-train-time-countdown"] = function()
    local w = world.make_world({seed = 42})
    world.spawn_bang(w, "barracks", {owner = 0, x = 5, y = 3})
    world.spawn_bang(w, "town-centre", {owner = 0, x = 3, y = 3})
    world.add_resource_bang(w, 0, "wood", 200)
    world.add_resource_bang(w, 0, "gold", 200)
    world.add_resource_bang(w, 0, "stone", 200)
    orders.issue_bang(w, orders.train(1, "knight"))
    local prod = world.world_get(w, 1, "producer")
    luaunit.assertEquals(prod.progress, 0)
    sim.tick_bang(w)
    local prod2 = world.world_get(w, 1, "producer")
    luaunit.assertTrue(prod2.progress > 0)
  end,

  ["test-cost-deduction-at-order"] = function()
    local w = world.make_world({seed = 42})
    world.spawn_bang(w, "barracks", {owner = 0, x = 5, y = 3})
    world.spawn_bang(w, "town-centre", {owner = 0, x = 3, y = 3})
    world.add_resource_bang(w, 0, "wood", 100)
    world.add_resource_bang(w, 0, "gold", 100)
    world.add_resource_bang(w, 0, "stone", 100)
    local cost = content.unit_cost("knight")
    local before_wood = world.resource_amount(w, 0, "wood")
    orders.issue_bang(w, orders.train(1, "knight"))
    sim.tick_bang(w)
    local after_wood = world.resource_amount(w, 0, "wood")
    luaunit.assertEquals(after_wood, before_wood - (cost.wood or 0))
  end,
}
